---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 28/03/2025 20:35
---

local Dialogs = {}
local CustomiseDialog = Navigator_CustomiseDialog -- from XML
local Nav = Navigator

function Dialogs:Init()
    CustomiseDialog:Init()
end

function CustomiseDialog:Show(bookmark)
    local customization = Nav.Bookmarks:GetCustomization(bookmark)
    local initialEditText = customization and customization.name or ""

    ZO_Dialogs_ShowDialog("NAVIGATOR_CUSTOMISEDIALOG",
            { node = bookmark:GetNode(), bookmark = bookmark, finishedCallback = null },
            { initialEditText = initialEditText, initialDefaultText = GetString(NAVIGATOR_CUSTOMISEDIALOG_NAME_INITIALTEXT)})
end

function CustomiseDialog:Init()
    --local function SetupDialog(dialog, data)
        --CustomiseDialog.selectSound = CustomiseDialog:GetNamedChild("SelectSound")
        --CustomiseDialog.selectedSoundID = self:GetSoundValue(data.category, data.key)
        --CustomiseDialog.selectSound.dropdown:SetSelectedItemText(self:GetSoundName(customControl.selectedSoundID))
    --end

    local function OnDialogSetup(dialog, data, textParams)
        dialog.data = data
        local node = data.node

        local containerControl = dialog:GetNamedChild("Container")
        local textControl = dialog:GetNamedChild("Text")
        local name = node:GetName()
        local suffix = node.zoneSuffix or node:GetSuffix()
        if suffix ~= nil and suffix ~= "" then
            local colour = ZO_ColorDef:New(node:GetSuffixColour(isSelected))
            name = name .. " " .. colour:Colorize(suffix)
        end

        local text = zo_strformat(GetString(NAVIGATOR_CUSTOMISEDIALOG_TEXT), name);
        textControl:SetText(text)

        local editControl = dialog:GetNamedChild("ContainerEditBox")
        editControl:SetTextType(TEXT_TYPE_ALL)
        editControl:SetMaxInputChars(30)

        local defaultText = textParams.initialDefaultText or ""
        editControl:SetDefaultText(defaultText)

        if textParams.initialEditText then
            editControl:SetText(textParams.initialEditText)
        end

        editControl:SelectAll()

        local function ColorPickerCallback(r, g, b, a)
            --containerControl:UpdateValue(false, r, g, b, a)
        end

        local iconColour = containerControl:GetNamedChild("IconColour")

        local iconColourRight = iconColour:GetNamedChild("Right")
        iconColourRight:SetHandler("OnMouseUp", function(self, btn, upInside)
            Nav.log("iconColourRight OnMouseUp")
            if upInside then
            end
        end)

            --iconColourBtn:SetHandler("OnMouseUp", function(self, btn, upInside)
        --    Nav.log("OnMouseUp")
        --    if upInside then
        --        local r, g, b, a = 1, 1, 1, 1 --colorpickerData.getFunc()
        --        zo_callLater(function()
        --            COLOR_PICKER:Show(ColorPickerCallback, r, g, b, a)
        --        end, 100)
        --    end
        --end)

        local iconColourTexture = iconColour:GetNamedChild("Texture")
        iconColourTexture:SetColor(1, 0, 0, 1)


    end

    local function OnDialogConfirm(dialog)
        --local node = dialog.data.node
        local editControl = dialog:GetNamedChild("ContainerEditBox")
        Nav.Bookmarks:SetAlias(dialog.data.bookmark, editControl:GetText())
        Nav.MapTab:ImmediateRefresh()
    end

    local function OnDialogDefault(dialog)
        --local node = dialog.data.node
        Nav.Bookmarks:SetAlias(dialog.data.bookmark, nil)
        Nav.MapTab:ImmediateRefresh()
    end

    ZO_Dialogs_RegisterCustomDialog("NAVIGATOR_CUSTOMISEDIALOG",
    {
        customControl = CustomiseDialog,
        title =
        {
            text = NAVIGATOR_MENU_CUSTOMISEBOOKMARK,
        },
        mainText =
        {
            text = "",
        },
        setup = OnDialogSetup,
        buttons =
        {
            {
                control = CustomiseDialog:GetNamedChild("ButtonsOk"),
                text = SI_OK,
                callback = OnDialogConfirm,
                keybind = "DIALOG_PRIMARY",
            },
            {
                control = CustomiseDialog:GetNamedChild("ButtonsCancel"),
                text = SI_DIALOG_CANCEL,
            },
            {
                control = CustomiseDialog:GetNamedChild("ButtonsDefault"),
                text = SI_COLLECTIONS_INVENTORY_DIALOG_DEFAULT_NAME,
                callback = OnDialogDefault,
                keybind = "DIALOG_SECONDARY",
            },
        }
    })
end


Nav.CustomiseDialog = CustomiseDialog
Nav.Dialogs = Dialogs