---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 13/06/2026 15:30
---
local Nav = Navigator

local MapTab = Nav.MapTab:Subclass()

function MapTab:Initialize(control)
    Nav.MapTab.Initialize(self, control)

    Nav.log(control:GetName() .. "[keyboard]:init")
    self:SetViewButtonTooltip()

    self.visible = false
    self.listControl = self.control:GetNamedChild("List")
    self.searchControl = self.control:GetNamedChild("Search")
    self.editControl = self.control:GetNamedChild("SearchEdit")
    self.viewButton = self.searchControl and self.searchControl:GetNamedChild("View")

    self.fragment = ZO_FadeSceneFragment:New(control)
    self.fragment.duration = 100

    ZO_ScrollList_AddDataType(self.listControl, 0, "Navigator_CategoryRow", 50, function(...) self:layoutCategoryRow(...) end, nil, nil, nil)
    ZO_ScrollList_AddDataType(self.listControl, 1, "Navigator_WayshrineRow", 25, function(...) self:layoutRow(...) end, nil, nil, nil)
    ZO_ScrollList_AddDataType(self.listControl, 2, "Navigator_CollapsedCategoryRow", 40, function(...) self:layoutCategoryRow(...) end, nil, nil, nil)
    ZO_ScrollList_AddDataType(self.listControl, 3, "Navigator_HintRow", 70, function(...) self:layoutHintRow(...) end, nil, nil, nil)

    self:SetHandlers()
    self:ApplyPerfectPixel(control)

    Nav.callback:RegisterCallback("OnMapChanged", function() self:OnMapChanged() end)
end

function Navigator_MainTab_OnInitialized(control)
    Nav.log("Navigator_MainTab_OnInitialized")
    Nav.mainTab = MapTab:New(control)
    control.tab = Nav.mainTab
    --Nav.log("Navigator_MainTab_OnInitialized: " .. (self or "null"))
    --Navigator.AttachMapTab("mainTab", self, Navigator.MapTab)
    --self:init()
end
