---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 13/06/2026 16:03
---
local Nav = Navigator

local MapTab = Nav.MapTab:Subclass()
--local MapTab = ZO_Object.MultiSubclass(Nav.MapTab, ZO_Gamepad_ParametricList_Search_Screen)

function MapTab:Initialize(control)
    Nav.log(control:GetName() .. "[gamepad]:init")
    Nav.MapTab.Initialize(self, control)

    --local ACTIVATE_ON_SHOW = true
    --ZO_Gamepad_ParametricList_Search_Screen.Initialize(self, BACKGROUND_LIST_FILTER_TARGET_FURNITURE_ID, "housingEditorTextSearch", control, ZO_GAMEPAD_HEADER_TABBAR_CREATE, ACTIVATE_ON_SHOW, GAMEPAD_HOUSING_FURNITURE_BROWSER_SCENE)

    --self:SetViewButtonTooltip()
    --
    --self.visible = false
    self.mainControl = self.control:GetNamedChild("Main")
    self.listControl = self.mainControl:GetNamedChild("List")
    self.searchControl = self.mainControl:GetNamedChild("Search")
    self.editControl = self.searchControl:GetNamedChild("BackdropEdit")
    --self.viewButton = self.searchControl and self.searchControl:GetNamedChild("View")

    self:InitializeKeybindDescriptor()

    self.fragment = ZO_SimpleSceneFragment:New(control)

    self.list = ZO_GamepadVerticalParametricScrollList:New(self.listControl)
    self.list:AddDataTemplate("Navigator_Gamepad_WayshrineRow", function(...) self:SetupRow(...) end, ZO_GamepadMenuEntryTemplateParametricListFunction)
    self.list:AddDataTemplateWithHeader("Navigator_Gamepad_WayshrineRow", ZO_SharedGamepadEntry_OnSetup, ZO_GamepadMenuEntryTemplateParametricListFunction, nil, "ZO_GamepadMenuEntryHeaderTemplate")
    self.list:SetAlignToScreenCenter(true)

    local function OnTargetChanged()
        --self.tooltipSelectedIndex = COMPLETION_ACTIVITY_DESCRIPTION_TOOLTIP_INDEX
        local targetData = self.list:GetTargetData()
        self.selectedData = targetData
        --if targetData then
        --    local completedActivities = ZO_ZoneStories_Manager.GetActivityCompletionProgressValues(targetData.zoneData.id, targetData.zoneCompletionType)
        --    if completedActivities > 0 then
        --        -- the first tooltip is the activity description tooltip so if we've already completed some of the
        --        -- activities for this type we want to skip to the next tooltip
        --        -- this should resolve to 1 and since we are guaranteed to have 2 tooltips it doesn't need to be validated
        --        self.tooltipSelectedIndex = self.tooltipSelectedIndex + 1
        --    end
        --end
        KEYBIND_STRIP:UpdateKeybindButtonGroup(self.keybindStripDescriptor)
        --self:UpdateTooltip()
    end
    self.list:SetOnTargetDataChangedCallback(OnTargetChanged)

    --self.fragment.duration = 100

    --ZO_ScrollList_AddDataType(self.listControl, 0, "Navigator_CategoryRow", 50, function(...) self:layoutCategoryRow(...) end, nil, nil, nil)
    --ZO_ScrollList_AddDataType(self.listControl, 1, "Navigator_WayshrineRow", 25, function(...) self:layoutRow(...) end, nil, nil, nil)
    --ZO_ScrollList_AddDataType(self.listControl, 2, "Navigator_CollapsedCategoryRow", 40, function(...) self:layoutCategoryRow(...) end, nil, nil, nil)
    --ZO_ScrollList_AddDataType(self.listControl, 3, "Navigator_HintRow", 70, function(...) self:layoutHintRow(...) end, nil, nil, nil)
    --
    --self:SetHandlers()
    --self:ApplyPerfectPixel(control)

    --Nav.callback:RegisterCallback("OnMapChanged", function() self:OnMapChanged() end)

    self.fragment:RegisterCallback("StateChange",  function(oldState, newState)
        if newState == SCENE_SHOWING then
            Nav.log(control:GetName() .. ": SCENE_SHOWING")
            Nav.lastTab = self
            self.visible = true
            if self.needsRefresh then
                self:ImmediateRefresh()
            else
                self:BuildList()
            end
            if Nav.Locations.keepsDirty then
                Nav.Locations:UpdateKeeps()
            end
            --if not self.listDisabled then
                self.list:Activate()
            --end
            self.list:RefreshVisible()
            KEYBIND_STRIP:AddKeybindButtonGroup(self.keybindStripDescriptor)
        elseif newState == SCENE_HIDDEN then
            Navigator.log(control:GetName() .. ": SCENE_HIDDEN")
            self.visible = false
            KEYBIND_STRIP:RemoveKeybindButtonGroup(self.keybindStripDescriptor)
            self.list:Deactivate()
        end
    end)
end

function MapTab:InitializeKeybindDescriptor()

    self.keybindStripDescriptor =
    {
        alignment = KEYBIND_STRIP_ALIGN_LEFT,
        {
            keybind = "UI_SHORTCUT_PRIMARY",

            name = function()
                if not self.selectedData then return "?" end
                local action = self.selectedData.node:GetActions()["singleClick"]
                Nav.log("InitializeKeybindDescriptor: %s -> %s '%s'", self.selectedData.node:GetName(), action, self.selectedData.node:GetActionDescription(action))
                return self.selectedData.node:GetActionDescription(action)
            end,

            callback = function()
                if self.selectedData then
                    --WORLD_MAP_MANAGER:SetMapByIndex(self.selectedData.index)
                    local action = self.selectedData.node:GetActions()["singleClick"]
                    self.selectedData.node:DoAction(action)
                    --SCENE_MANAGER:ShowBaseScene()
                    PlaySound(SOUNDS.MAP_LOCATION_CLICKED)
                end
            end,

            visible = function() return self.selectedData ~= nil end,
        },
        {
            name = GetString(SI_GAMEPAD_INVENTORY_ACTION_LIST_KEYBIND),
            keybind = "UI_SHORTCUT_TERTIARY",
            callback = function()
            end,
            visible = function() return self.selectedData ~= nil end,
        },
        {
            name = "Search",
            keybind = "UI_SHORTCUT_SECONDARY",
            callback = function()
                self.editControl:TakeFocus()
            end,
            visible = function() return true end
        }
    }

    ZO_Gamepad_AddBackNavigationKeybindDescriptors(self.keybindStripDescriptor, GAME_NAVIGATION_TYPE_BUTTON, ZO_WorldMapInfo_OnBackPressed)
end

function MapTab:RefreshKeybind()
    if self.keybindStripDescriptor then
        KEYBIND_STRIP:UpdateKeybindButtonGroup(self.keybindStripDescriptor)
    end
end

function MapTab:SetupRow(control, data, selected, selectedDuringRebuild, enable, activated)
    Nav.log("SetupRow %s", data.node.name)
    ZO_SharedGamepadEntry_OnSetup(control, data, selected, selectedDuringRebuild, enable, activated)
    if selected then
        self.selectedData = data
        --self:SetupLocationDetails(data)
    end

    local icon = control:GetNamedChild("Overlay")
    local overlayIcon, overlayColour = data.node:GetOverlayIcon(selected)
    if overlayIcon then
        icon:SetColor(ZO_ColorDef.HexToFloats(overlayColour))
        icon:SetTexture(overlayIcon)
        icon:SetHidden(false)
    else
        icon:SetHidden(true)
    end
end

function MapTab:BuildCategory(category)
    local collapsed = self.collapsedCategories[category.id] and true or false
    local list = category.list

    --self:BuildCategoryHeader(scrollData, category.id, category.title, collapsed)
    local categoryTitle = tonumber(category.title) ~= nil and GetString(category.title) or category.title

    if collapsed then
        return
    elseif #list == 0 and category.emptyHint then
        list = {{ hint = GetString(category.emptyHint) }}
    end

    local currentNodeIndex = self.resultCount
    local includeUnknown = Nav.saved.includeUndiscovered or self.currentView == "all"
    local listed = 0

    for i = 1, #list do
        if list[i].hint then
            --local entry = ZO_ScrollList_CreateDataEntry(3, { hint = list[i].hint })
            --table.insert(scrollData, entry)
        elseif list[i]:IsKnown() or includeUnknown then
            local data = {
                node = list[i],
                indexInCategory = i,
                categoryEntryCount = #list,
                nodeIndex = currentNodeIndex
            }

            --local entry = ZO_ScrollList_CreateDataEntry(1, data, category.id)
            --table.insert(scrollData, entry)
            local entryData = ZO_GamepadEntryData:New(data.node:GetName(), data.node:GetIcon())
            entryData:SetDataSource(data)
            if data.node:GetSuffix() ~= "" then
                entryData:AddSubLabel(data.node:GetSuffix())
            end

            local overlayIcon, overlayColour = data.node:GetOverlayIcon(true)
            entryData:SetCooldownIcon(overlayIcon)

            if categoryTitle then
                --Nav.log("Add entry %s header %s", data.node.name, categoryTitle)
                entryData:SetHeader(categoryTitle)
                categoryTitle = nil
                self.list:AddEntry("Navigator_Gamepad_WayshrineRow", entryData)
            else
                --Nav.log("Add entry %s", data.node.name)
                self.list:AddEntry("Navigator_Gamepad_WayshrineRow", entryData)
            end

            currentNodeIndex = currentNodeIndex + 1
            listed = listed + 1

            if category.maxEntries and listed >= category.maxEntries then
                break
            end
        end
    end

    --if #list > 0 and listed == 0 and (self.currentView == nil or self.currentView ~= "all") then
    --    local entry = ZO_ScrollList_CreateDataEntry(3,{
    --        hint = GetString(NAVIGATOR_HINT_SHOWUNDISCOVERED),
    --        onClick = function() self:ShowUndiscovered() end
    --    })
    --    table.insert(scrollData, entry)
    --end

    self.resultCount = currentNodeIndex
end

function MapTab:BuildList()
    self.list:Clear()

    --local mapData = self.data:GetLocationList()
    --
    --for i, mapEntry in ipairs(mapData) do
    --    local entryData = ZO_GamepadEntryData:New(mapEntry.locationName)
    --    entryData:SetDataSource(mapEntry)
    --    self.list:AddEntry("ZO_GamepadMenuEntryTemplateLowercase42", entryData)
    --end
    self.resultCount = 0
    for i = 1, #self.content do
        local category = self.content[i]
        self:BuildCategory(category)
    end

    self.list:Commit()

    self:UpdateEditDefaultText()
end

function MapTab:UpdateContent(searchString, keepTargetNode)
    self.searchString = searchString

    local zone = Nav.Locations:getCurrentMapZone()
    self.content = Nav.ViewManager:Build(self.searchString, self.currentView, zone)

    self:BuildList(keepTargetNode)
end

function MT:UpdateEditDefaultText()
    if not self.editControl then return end

    local searchString = self.editControl:GetText()
    if searchString == "" then
        -- reinstate default text
        --local openTabBinding = ZO_Keybindings_GetHighestPriorityNarrationStringFromAction("NAVIGATOR_FOCUSSEARCH") or '-'
        --local s = zo_strformat(self.editControl:HasFocus() and GetString(NAVIGATOR_SEARCH) or GetString(NAVIGATOR_SEARCH_KEYPRESS),
        --        openTabBinding)
        local s = GetString(NAVIGATOR_SEARCH)
        ZO_EditDefaultText_Initialize(self.editControl, s)
    else
        -- remove default text
        ZO_EditDefaultText_Disable(self.editControl)
    end
end

function Navigator_MainTab_Gamepad_OnInitialized(control)
    Nav.log("Navigator_MainTab_Gamepad_OnInitialized")
    Nav.mainTab_gamepad = MapTab:New(control)
    control.tab = Nav.mainTab_gamepad
    --Nav.log("Navigator_MainTab_OnInitialized: " .. (self or "null"))
    --Navigator.AttachMapTab("mainTab", self, Navigator.MapTab)
    --self:init()
end
